//! Static, curated set of strings emitted by common runtime libraries.
//!
//! When analyzing a binary, the vast majority of static strings come
//! from statically-linked CRT / libc / Windows-API boilerplate —
//! error messages, DLL names, function names, format strings — not
//! from anything the program author wrote. Filtering these out makes
//! the output of a real triage workflow much more readable.
//!
//! This module ships a hand-curated allow-list of the most common
//! library-emitted strings across:
//!
//! * **MSVC C/C++ runtime** — error messages, abort handlers, runtime
//!   diagnostics, parameter-validation strings.
//! * **glibc / musl libc** — assertion failures, errno strings, common
//!   symbol names that leak into rodata when not stripped.
//! * **Windows API names** — DLL filenames and imported function
//!   names that appear in PE import tables.
//! * **Standard libc symbol names** — `__libc_start_main`,
//!   `__cxa_atexit`, etc., that ELF dynamic linkers expose.
//!
//! It is deliberately conservative: we'd rather pass through a
//! library string than swallow a meaningful program string. A binary
//! signature / FLIRT-style approach would catch more, but ship-cost
//! is much higher; this list closes the 80% case.
//!
//! The set is checked exactly (case-sensitive). The cost is a single
//! `phf`-free `HashSet` lookup per static string.

use std::collections::HashSet;
use std::sync::OnceLock;

/// Returns `true` if `s` matches a known library / runtime / API
/// boilerplate string.
///
/// Intended for use after static-string extraction to suppress noise
/// in analyst-facing output. Decoded / stack / tight strings are
/// never matched against this list because they're recovered from
/// runtime computation, not static rodata.
pub fn is_library_string(s: &str) -> bool {
    library_set().contains(s)
}

fn library_set() -> &'static HashSet<&'static str> {
    static SET: OnceLock<HashSet<&'static str>> = OnceLock::new();
    SET.get_or_init(|| LIBRARY_STRINGS.iter().copied().collect())
}

/// The raw allow-list. Exposed for callers that want to introspect
/// what's filtered.
pub const LIBRARY_STRINGS: &[&str] = &[
    // ---- MSVC C runtime error/diagnostic messages ----
    "Microsoft Visual C++ Runtime Library",
    "Runtime Error!",
    "Program: ",
    "abort() has been called",
    "argument list too long",
    "Argument out of domain",
    "Numerical argument out of domain",
    "Numerical result out of range",
    "Result too large",
    "Floating point error",
    "Domain error",
    "Range error",
    "Stack overflow",
    "Heap corruption",
    "Buffer too small",
    "Invalid parameter",
    "Possible heap pointer freed",
    "DAMAGE: after Normal block",
    "DAMAGE: after Free block",
    "DAMAGE: before Normal block",
    "DAMAGE: before Free block",
    "Invalid heap argument",
    "Invalid file argument",
    "Invalid data",
    "Bad allocation",
    "An application has made an attempt to load the C runtime library incorrectly.",
    "Please contact the application's support team for more information.",
    "This application has requested the Runtime to terminate it in an unusual way.",
    "R6002\n- floating point support not loaded\n",
    "R6008\n- not enough space for arguments\n",
    "R6009\n- not enough space for environment\n",
    "R6010\n- abort() has been called\n",
    "R6016\n- not enough space for thread data\n",
    "R6017\n- unexpected multithread lock error\n",
    "R6018\n- unexpected heap error\n",
    "R6019\n- unable to open console device\n",
    "R6024\n- not enough space for _onexit/atexit table\n",
    "R6025\n- pure virtual function call\n",
    "R6026\n- not enough space for stdio initialization\n",
    "R6027\n- not enough space for lowio initialization\n",
    "R6028\n- unable to initialize heap\n",
    "R6030\n- CRT not initialized\n",
    "R6031\n- Attempt to initialize the CRT more than once.\nThis indicates a bug in your application.\n",
    "R6032\n- not enough space for locale information\n",
    "R6033\n- Attempt to use MSIL code from this assembly during native code initialization\n",
    "R6034\n- inconsistent onexit begin-end variables\n",
    "GetLastActivePopup",
    "GetActiveWindow",
    "MessageBoxA",
    // ---- libc / glibc / musl symbol names ----
    "__libc_start_main",
    "__cxa_atexit",
    "__cxa_finalize",
    "__libc_init",
    "__libc_csu_init",
    "__libc_csu_fini",
    "__gmon_start__",
    "__deregister_frame_info",
    "__register_frame_info",
    "_ITM_deregisterTMCloneTable",
    "_ITM_registerTMCloneTable",
    "_Jv_RegisterClasses",
    "__rtld_lazy",
    "_DYNAMIC",
    "_GLOBAL_OFFSET_TABLE_",
    "_init",
    "_fini",
    "_start",
    "_edata",
    "_end",
    "__bss_start",
    "__data_start",
    "__dso_handle",
    "completed.0",
    "completed.6661",
    "completed.7283",
    "deregister_tm_clones",
    "register_tm_clones",
    "frame_dummy",
    "__do_global_dtors_aux",
    "__do_global_dtors_aux_fini_array_entry",
    "__frame_dummy_init_array_entry",
    "__TMC_END__",
    "__FRAME_END__",
    "__GNU_EH_FRAME_HDR",
    "__init_array_end",
    "__init_array_start",
    "__fini_array_end",
    "__fini_array_start",
    "__libc_atexit",
    "__libc_subfreeres",
    "__libc_subinit",
    "GLIBC_2.0",
    "GLIBC_2.1",
    "GLIBC_2.2",
    "GLIBC_2.2.5",
    "GLIBC_2.3",
    "GLIBC_2.4",
    "GLIBC_2.7",
    "GLIBC_2.10",
    "GLIBC_2.14",
    "GLIBC_2.17",
    "GLIBC_2.18",
    "GLIBC_2.27",
    "GLIBC_2.28",
    "GLIBC_2.34",
    "libc.so.6",
    "libc.so.7",
    "libpthread.so.0",
    "libm.so.6",
    "libdl.so.2",
    "ld-linux.so.2",
    "ld-linux-x86-64.so.2",
    "ld-linux-aarch64.so.1",
    "(null)",
    "Out of memory",
    "Cannot allocate memory",
    "Segmentation fault",
    "Bus error",
    "Floating point exception",
    "Illegal instruction",
    "Aborted",
    "Killed",
    "Terminated",
    // ---- Toolchain marker strings ----
    "GCC: (",
    "GCC: (GNU)",
    "GCC: (Ubuntu",
    "GCC: (Debian",
    "GCC: (Alpine",
    "GCC: (Red Hat",
    "clang version",
    "Linker:",
    "Linker: LLD",
    // ---- Windows DLL filenames (most-imported set) ----
    "kernel32.dll",
    "KERNEL32.dll",
    "KERNEL32.DLL",
    "user32.dll",
    "USER32.dll",
    "USER32.DLL",
    "advapi32.dll",
    "ADVAPI32.dll",
    "ADVAPI32.DLL",
    "ntdll.dll",
    "NTDLL.dll",
    "NTDLL.DLL",
    "msvcrt.dll",
    "MSVCRT.dll",
    "MSVCRT.DLL",
    "msvcr80.dll",
    "msvcr90.dll",
    "msvcr100.dll",
    "msvcr110.dll",
    "msvcr120.dll",
    "msvcp80.dll",
    "msvcp90.dll",
    "msvcp100.dll",
    "msvcp110.dll",
    "msvcp120.dll",
    "vcruntime140.dll",
    "VCRUNTIME140.dll",
    "ucrtbase.dll",
    "ucrtbased.dll",
    "api-ms-win-crt-runtime-l1-1-0.dll",
    "api-ms-win-crt-string-l1-1-0.dll",
    "api-ms-win-crt-stdio-l1-1-0.dll",
    "api-ms-win-crt-heap-l1-1-0.dll",
    "api-ms-win-crt-math-l1-1-0.dll",
    "api-ms-win-crt-convert-l1-1-0.dll",
    "api-ms-win-crt-time-l1-1-0.dll",
    "api-ms-win-crt-utility-l1-1-0.dll",
    "api-ms-win-crt-locale-l1-1-0.dll",
    "api-ms-win-crt-filesystem-l1-1-0.dll",
    "api-ms-win-crt-environment-l1-1-0.dll",
    "api-ms-win-crt-multibyte-l1-1-0.dll",
    "shell32.dll",
    "SHELL32.dll",
    "ole32.dll",
    "OLE32.dll",
    "oleaut32.dll",
    "OLEAUT32.dll",
    "ws2_32.dll",
    "WS2_32.dll",
    "WSOCK32.dll",
    "wininet.dll",
    "WININET.dll",
    "winhttp.dll",
    "WINHTTP.dll",
    "shlwapi.dll",
    "SHLWAPI.dll",
    "psapi.dll",
    "PSAPI.dll",
    "comctl32.dll",
    "COMCTL32.dll",
    "comdlg32.dll",
    "COMDLG32.dll",
    "gdi32.dll",
    "GDI32.dll",
    "rpcrt4.dll",
    "RPCRT4.dll",
    "secur32.dll",
    "SECUR32.dll",
    "version.dll",
    "VERSION.dll",
    "iphlpapi.dll",
    "IPHLPAPI.dll",
    "imagehlp.dll",
    "IMAGEHLP.dll",
    "dbghelp.dll",
    "DBGHELP.dll",
    "userenv.dll",
    "USERENV.dll",
    // ---- The Windows-API names this DLL list pulls in by themselves ----
    "GetProcAddress",
    "LoadLibraryA",
    "LoadLibraryW",
    "LoadLibraryExA",
    "LoadLibraryExW",
    "GetModuleHandleA",
    "GetModuleHandleW",
    "GetModuleFileNameA",
    "GetModuleFileNameW",
    "FreeLibrary",
    "GetLastError",
    "SetLastError",
    "ExitProcess",
    "TerminateProcess",
    "GetCurrentProcess",
    "GetCurrentProcessId",
    "GetCurrentThread",
    "GetCurrentThreadId",
    "OpenProcess",
    "CreateThread",
    "CreateProcessA",
    "CreateProcessW",
    "WaitForSingleObject",
    "WaitForMultipleObjects",
    "CloseHandle",
    "DuplicateHandle",
    "Sleep",
    "GetTickCount",
    "GetTickCount64",
    "QueryPerformanceCounter",
    "QueryPerformanceFrequency",
    "GetSystemTimeAsFileTime",
    "GetSystemTime",
    "GetLocalTime",
    "SetUnhandledExceptionFilter",
    "UnhandledExceptionFilter",
    "RtlCaptureContext",
    "RtlVirtualUnwind",
    "RtlLookupFunctionEntry",
    "RtlAddFunctionTable",
    "RtlPcToFileHeader",
    "IsDebuggerPresent",
    "IsProcessorFeaturePresent",
    "DebugBreak",
    "OutputDebugStringA",
    "OutputDebugStringW",
    "GetCommandLineA",
    "GetCommandLineW",
    "GetEnvironmentStringsW",
    "GetEnvironmentVariableA",
    "GetEnvironmentVariableW",
    "SetEnvironmentVariableA",
    "SetEnvironmentVariableW",
    "FreeEnvironmentStringsW",
    "GetStartupInfoA",
    "GetStartupInfoW",
    "GetStdHandle",
    "SetStdHandle",
    "WriteConsoleA",
    "WriteConsoleW",
    "ReadConsoleA",
    "ReadConsoleW",
    "WriteFile",
    "ReadFile",
    "CreateFileA",
    "CreateFileW",
    "CreateFileMappingA",
    "CreateFileMappingW",
    "MapViewOfFile",
    "UnmapViewOfFile",
    "SetFilePointer",
    "SetFilePointerEx",
    "GetFileSize",
    "GetFileSizeEx",
    "GetFileType",
    "FlushFileBuffers",
    "GetFileAttributesA",
    "GetFileAttributesW",
    "FindFirstFileA",
    "FindFirstFileW",
    "FindNextFileA",
    "FindNextFileW",
    "FindClose",
    "DeleteFileA",
    "DeleteFileW",
    "MoveFileA",
    "MoveFileW",
    "CopyFileA",
    "CopyFileW",
    "CreateDirectoryA",
    "CreateDirectoryW",
    "RemoveDirectoryA",
    "RemoveDirectoryW",
    "GetCurrentDirectoryA",
    "GetCurrentDirectoryW",
    "SetCurrentDirectoryA",
    "SetCurrentDirectoryW",
    "VirtualAlloc",
    "VirtualAllocEx",
    "VirtualFree",
    "VirtualFreeEx",
    "VirtualProtect",
    "VirtualProtectEx",
    "VirtualQuery",
    "VirtualQueryEx",
    "HeapAlloc",
    "HeapFree",
    "HeapCreate",
    "HeapDestroy",
    "HeapReAlloc",
    "GetProcessHeap",
    "LocalAlloc",
    "LocalFree",
    "LocalReAlloc",
    "GlobalAlloc",
    "GlobalFree",
    "GlobalReAlloc",
    "GetUserNameA",
    "GetUserNameW",
    "GetComputerNameA",
    "GetComputerNameW",
    "GetTempPathA",
    "GetTempPathW",
    "GetTempFileNameA",
    "GetTempFileNameW",
    "EnterCriticalSection",
    "LeaveCriticalSection",
    "InitializeCriticalSection",
    "DeleteCriticalSection",
    "InitializeCriticalSectionAndSpinCount",
    "TryEnterCriticalSection",
    "InitOnceBeginInitialize",
    "InitOnceComplete",
    "InitOnceExecuteOnce",
    "TlsAlloc",
    "TlsFree",
    "TlsGetValue",
    "TlsSetValue",
    "FlsAlloc",
    "FlsFree",
    "FlsGetValue",
    "FlsSetValue",
    "EncodePointer",
    "DecodePointer",
    "InterlockedExchange",
    "InterlockedIncrement",
    "InterlockedDecrement",
    "InterlockedCompareExchange",
    "RaiseException",
    "TerminateThread",
    "RegOpenKeyExA",
    "RegOpenKeyExW",
    "RegCloseKey",
    "RegQueryValueExA",
    "RegQueryValueExW",
    "RegSetValueExA",
    "RegSetValueExW",
    "RegDeleteValueA",
    "RegDeleteValueW",
    "RegCreateKeyExA",
    "RegCreateKeyExW",
    "RegEnumKeyExA",
    "RegEnumKeyExW",
    "RegEnumValueA",
    "RegEnumValueW",
    "WSAStartup",
    "WSACleanup",
    "WSAGetLastError",
    "socket",
    "bind",
    "listen",
    "accept",
    "connect",
    "send",
    "recv",
    "sendto",
    "recvfrom",
    "closesocket",
    "shutdown",
    "gethostbyname",
    "gethostname",
    "inet_addr",
    "inet_ntoa",
    "htons",
    "ntohs",
    "htonl",
    "ntohl",
    "InternetOpenA",
    "InternetOpenW",
    "InternetOpenUrlA",
    "InternetOpenUrlW",
    "InternetReadFile",
    "InternetCloseHandle",
    "HttpOpenRequestA",
    "HttpOpenRequestW",
    "HttpSendRequestA",
    "HttpSendRequestW",
    "memcpy",
    "memmove",
    "memcmp",
    "memset",
    "strcpy",
    "strncpy",
    "strcmp",
    "strncmp",
    "strlen",
    "strcat",
    "strncat",
    "strchr",
    "strrchr",
    "strstr",
    "sprintf",
    "snprintf",
    "vsprintf",
    "vsnprintf",
    "printf",
    "fprintf",
    "vprintf",
    "vfprintf",
    "scanf",
    "fscanf",
    "sscanf",
    "fopen",
    "fclose",
    "fread",
    "fwrite",
    "fseek",
    "ftell",
    "fflush",
    "fgets",
    "fputs",
    "fgetc",
    "fputc",
    "getc",
    "putc",
    "getchar",
    "putchar",
    "atoi",
    "atol",
    "atoll",
    "atof",
    "strtol",
    "strtoll",
    "strtoul",
    "strtoull",
    "strtod",
    "strtof",
    "malloc",
    "calloc",
    "realloc",
    "free",
    "exit",
    "_exit",
    "abort",
    "system",
    "getenv",
    "setenv",
    "putenv",
    "rand",
    "srand",
];
